### ISSUE TITLE
Getting this .gitmodules error when uploading to Heroku

### ISSUE THREAD

**Issue by ismaelc** [hirako2000/hackathon-board#1]
-----> Using set buildpack heroku/nodejs
-----> Node.js app detected
-----> Creating runtime environment

```
   NPM_CONFIG_LOGLEVEL=error
   NPM_CONFIG_PRODUCTION=true
   NODE_ENV=production
   NODE_MODULES_CACHE=true
```

-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)

```
   Resolving node version (latest stable) via semver.io...
   Downloading and installing node 5.11.1...
   Using default npm version: 3.8.6
```

-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)
       npm ERR! git submodule -q update --init --recursive: No submodule mapping found in .gitmodules for path 'support/web-socket-js'
       npm ERR! git submodule -q update --init --recursive:
       npm ERR! git submodule -q update --init --recursive: No submodule mapping found in .gitmodules for path 'support/web-socket-js'
       npm ERR! git submodule -q update --init --recursive:
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/engine.io-client.git /app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8: Cloning into bare repository '/app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8'...
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/engine.io-client.git /app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8: Host key verification failed.
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/engine.io-client.git /app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8: fatal: Could not read from remote repository.
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/engine.io-client.git /app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8:
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/engine.io-client.git /app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8: Please make sure you have the correct access rights
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/engine.io-client.git /app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8: and the repository exists.
       npm ERR! Linux 3.13.0-85-generic
       npm ERR! argv "/tmp/build_49684ac2b17943662e53ffdaaf000ed7/.heroku/node/bin/node" "/tmp/build_49684ac2b17943662e53ffdaaf000ed7/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_49684ac2b17943662e53ffdaaf000ed7/.npmrc"
       npm ERR! node v5.11.1
       npm ERR! npm  v3.8.6
       npm ERR! code 128

```
   npm ERR! Command failed: git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/engine.io-client.git /app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8
   npm ERR! Cloning into bare repository '/app/.npm/_git-remotes/git-github-com-bitpay-engine-io-client-git-bitpay-1-5-4-534e88e8'...
   npm ERR! Host key verification failed.
   npm ERR! fatal: Could not read from remote repository.
   npm ERR!
   npm ERR! Please make sure you have the correct access rights
   npm ERR! and the repository exists.
   npm ERR!
   npm ERR!
   npm ERR! If you need help, you may report this error at:
   npm ERR!     <https://github.com/npm/npm/issues>

   npm ERR! Please include the following file with any support request:
   npm ERR!     /tmp/build_49684ac2b17943662e53ffdaaf000ed7/npm-debug.log
```

-----> Build failed

```
   We're sorry this build is failing! You can troubleshoot common issues here:
   https://devcenter.heroku.com/articles/troubleshooting-node-deploys

   Some possible problems:

   - Node version not specified in package.json
   https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

   Love,
   Heroku
```

 !     Push rejected, failed to compile Node.js app

**Comment by hirako2000** [comment]
Hi, seems to be due to this npm [issue](https://github.com/npm/npm/issues/11890) with bitcore
Can you try specifying some npm engine in package.json?

```

  "engines" : { 
    "npm" : "~3.5.3" 
  }

```

**Comment by hirako2000** [comment]
@ismaelc, I removed this lib altogether and added a few missing deps. Tested with the latest version of npm and node, it now works fine locally.
I can't check with Heroku right now but I believe things should be sorted now.

**Comment by ismaelc** [comment]
Works now! Found another unrelated issue though, will post separately. Thanks for the prompt response!
